apiVersion: batch.hpw.cloud/v1alpha1
kind: Job
metadata:
  name: test-job-webhook-disallow
spec:
  minAvailable: 4
  taskSpecs:
  - replicas: 2
    name: task-1
    template:
      metadata:
        name: web-1
      spec:
        containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            requests:
              cpu: "1"
        restartPolicy: OnFailure
        schedulerName: kube-batch
  - replicas: 2
    name: task-1
    template:
      metadata:
        name: web-1
      spec:
        containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            requests:
              cpu: "1"
        restartPolicy: OnFailure
        schedulerName: kube-batch