basic:
  image_tag_version: "latest"
  controller_image_name: "kubesigs/vk-controllers"
  scheduler_image_name: "kubesigs/kube-batch"
  admission_image_name: "kubesigs/vk-admission"
  admission_secret_name: "volcano-admission-secret"
  image_pull_secret: ""
