apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-custom-job
webhooks:
- clientConfig:
    #caBundle should be provided accordingly, inverted from ca.crt; 
    caBundle: {{ca.crt}}
    
    # When using clientConfig.service, the server cert must be valid for <svc_name>.<svc_namespace>.svc
    # service:
    #  name: webhook-service
    #  namespace: webhook
    #  path: /jobs

    # the url should agree with webhook service
    url: https://{{hostIP}}:32222/jobs
  failurePolicy: Ignore
  name: validcontainer.k8s.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - "batch.hpw.cloud"
    apiVersions:
    - "v1alpha1"
    operations:
    - CREATE
    resources:
    - jobs


