apiVersion: v1
kind: Namespace
metadata:
  name: admission
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admission-controller
    admission: "true"
  name: admission-controller
  namespace: admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller
      admission: "true"
  template:
    metadata:
      labels:
        app: admission-controller
        admission: "true"
    spec:
      containers:
      - args:
        - --tls-cert-file=/admission.local.config/certificates/tls.crt
        - --tls-private-key-file=/admission.local.config/certificates/tls.key
        - --alsologtostderr
        - --port=443
        - -v=4
        - 2>&1
        image: admission-controller-server:1.0
        imagePullPolicy: IfNotPresent
        name: admission-controller
        volumeMounts:
        - mountPath: /admission.local.config/certificates
          name: admission-certs
          readOnly: true
      volumes:
      - name: admission-certs
        secret:
          defaultMode: 420
          secretName: admission-controller-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    test: admission
  name: admission-service
  namespace: admission
spec:
  ports:
  - port: 443
    nodePort: 32222
    protocol: TCP
    targetPort: 443
  selector:
    admission: "true"
  sessionAffinity: None
  type: NodePort
